# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Clg7jz8VObBaqHwaQS_oE87aZE0pGp9
"""

import numpy as np


def ES(losses, alpha=None, VaR=None):
    if VaR is None:
        VaR = np.percentile(losses, 100 * alpha)

    es_value = np.mean(losses[losses > VaR])
    return es_value