# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Clg7jz8VObBaqHwaQS_oE87aZE0pGp9
"""

def WhoAmI():
    return 'yr2505'